baseurl: https://vanpariyar.in
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Ronak Vanpariya

languages:
    en:
        languageName: English
        title: Ronak Vanpariya
        weight: 1
    # zh-cn:
    #     languageName: 中文
    #     title: 演示站点
    #     weight: 2
    # ar:
    #     languageName: عربي
    #     languagedirection: rtl
    #     title: موقع تجريبي
    #     weight: 3

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics: G-T7YMQ8HWGV

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

#various options
# enableGitInfo: true
enableEmoji: true
publishDir: "docs"

permalinks:
    # post: /blog/:slug/
    # blog: 
    page: /:slug/

taxonomies:
    author: author
    tag: tags
    category: categories

params:
    mainSections:
        - blog
    featuredImageField: image
    rssFullContent: true
    favicon: ./images/favicon.png

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🙂
        subtitle: Just a simple person and Programmer :).
        avatar:
            enabled: true
            local: false
            src: https://avatars1.githubusercontent.com/u/26689210?s=460&u=7532c1409e49827c72a8b59b2e0f8f139f5ba9f3&v=4

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo: vanpariyar/myblog
            issueTerm: pathname
            label: comment

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site: VanpariyaRonakJ

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/vanpariyar
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/vanpariyaronakj
          params:
              icon: brand-twitter

        - identifier: facebook
          name: facebook
          url: https://facebook.com/ronak.vanpariya.12
          params:
              icon: brand-facebook

        - identifier: instagram
          name: instagram
          url: https://instagram.com/ronak_vanpariya
          params:
              icon: brand-instagram
        
        - identifier: linkedin
          name: linkedin
          url: https://www.linkedin.com/in/ronak-vanpariya
          params:
              icon: brand-linkedin

        - identifier: mail
          name: mail
          url: 'mailto:ronak@vanpariyar.in'
          params:
              icon: brand-mail

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
